### ISSUE TITLE
Build Argument for OpenHV version

### ISSUE THREAD

**Issue by EchedelleLR** [OpenHV/Server#1]
In the Dockerfile I have hosted at Codeberg still using Mono, the OpenHV version is setup by a build argument.

Why not doing here the same and make it defined through a TAG of the other repo in the CI here?

**Comment by Mailaender** [comment]
Because I wanted people to download the `Dockerfile` and built themselves. The correct version is vital for the game, so any mix up by wrong user input would break the game. A tag should just work.
